### ISSUE TITLE
[License Issue] Please update your license statement about using Apache SkyWalking

### ISSUE THREAD

**Issue by wu-sheng** [huaweicloud/Sermant#164]
Hi, Huawei Cloud `java-mesh` team,

I noticed this project is using Apache SkyWalking Java agent's core, APIs, plugin system and some more design. As an Apache 2.0 License project, we are good you are depending our core to do more.
But, you should know that, by following the Apache 2.0 License, you should declare you are building your agent on the top of Apache SkyWalking's Java agent. By reading how you are using, the whole agent side is an extension.
Please update your readme and License file to make this clear, by following APLv2 requirements.

Sheng Wu, on behalf of Apache SkyWalking PMC.

**Comment by wang-yeliang** [comment]
Looking forward to the follow-up

**Comment by yangyshdan** [comment]
Hi  @wu-sheng . Thanks for the information. 

We just did a quick investigation, we indeed found that some code is built directly on the project Apache SkyWalking. We are sincerely sorry for missing the License header for ASF for this part of code.

We are now following this issue. The following actions will include:
1. Add the clarification about the relationship between this project and Apache SkyWalking in the project's readme.md.
2. Add the License header for ASF for all the source code, which is built based on Apache SkyWalking.

We will invite Apache SkyWalking team to review the following PRs related to Apache SkyWalking, if the team's time permits.

This open source project is far from being mature, we thank Apache SkyWalking and such projects which help us better devote in the open source community !

**Comment by wu-sheng** [comment]
Thanks for updating. Hope this license issue could be resolved soon and clearly.

**Comment by yangyshdan** [comment]
@wu-sheng , would you please check the fix of the readme.md issue per the PR above?  Thanks.

This is regard to the action: 
_“Add the clarification about the relationship between this project and Apache SkyWalking in the project's readme.md.”_

We have made two major changes. 
1) Add the relationship between this project and Apache SkyWalking along with other related projects in the **Declaration** section.
2) Translate the README into English. Part of the reason is to express idea  to the license issue precisely. 

Other more actions for _"Adding the License header for ASF"_ will come soon.

**Comment by wu-sheng** [comment]
Good to see this. Besides the License header recovering, there are 2 License issues should be fixed too
1. License or Notice in the root, as the license of source codes, should declare which files and copied(maybe modified later) are originally from Apache SkyWalking. As what I was told, Java-mesh could not just do maven dependency.
2. You should provide the binary license. I know this project is not released, but that is an item of TODO list. In that list, you should declare, you are redistributing Apache SkyWalking, especially its Java agent.

**Comment by WillemJiang** [comment]
According to ASF [Assembling LICENSE and NOTICE files guide](https://infra.apache.org/licensing-howto.html), there are two part of Licenses file we need to care about, one is for the code release, the other is for binary release, as we may have two different ['bundled'](https://infra.apache.org/licensing-howto.html#bundled-vs-non-bundled) third party artifacts.  

For the code release kit we need include the third party project's license declaration in the source release kit License file if we have the third party source code included.
For the binary code release, as we include the third party jars include the kit, we need to list those jars License information in the License file. It's quit easy to do that by using the [License maven plugin with the configration](https://github.com/apache/servicecomb-pack/blob/master/pom.xml#L640) like here, you can get the third party License description file in the assembly directory.

For the NOTICE file part, here is [a discussion](https://opensource.stackexchange.com/questions/7872/how-to-properly-assemble-notice-file-for-new-software-under-apache-license-2-0/) you can take a look. 

You can take these two License files as an example:
* [License for source release](https://github.com/apache/servicecomb-pack/blob/master/LICENSE)
* [License for binary release](https://github.com/apache/servicecomb-pack/blob/master/distribution/src/release/LICENSE)

**Comment by yangyshdan** [comment]
Hello, @wu-sheng , would you please take a review at PR #191 ?  Thanks.

In this PR, we have 1) applied the ASF license header to the files that are copied from Apache SkyWalking, and 2) updated the LICENSE file accordingly. Other changes such as binary license will also come later.

**Comment by wu-sheng** [comment]
I left comments there. There are some pieces missing there. Some mechanics changed, but the skeletons are there.

**Comment by yangyshdan** [comment]
Just put a comment here for TODO list for later following-up. Later discussion might be followed by PRs.

Currently there are mainly 3 parts of works that needs to be corrected. 

- [ ] The javaagent's plugin design architecture is referred to Apache Skywalking. This needs to be mentioned in README or somewhere else.
- [ ] Some classes from the agent core project are copied from Apache Skywalking, but with wrong declaration way.  Correct legal header needs to be updated in these files. 
    -  These classes from agent core are mainly located in `com.huawei.javamesh.core.agent`. 
    -  Corresponding classes related to instrumentation in plugin modules - needs to be listed as well.
    -  Put the summaries in the LICENSE file.
- [ ] Need to list those jars License information in the License file in the binary release.

**Comment by yangyshdan** [comment]
Hi all, the issue should be fixed and will be closed this time. Should there be any remaining problem, please let me know.
