### ISSUE TITLE
【Question】对开源项目中使用或修改第三方依赖源码或二进制文件的思考

### ISSUE THREAD

**Issue by HapThorin** [huaweicloud/Sermant#192]
在开源项目中基于第三方依赖源码或源码片段，开发自己功能的情况很常见，比如[Spark](https://github.com/apache/spark)的[TimSort.java](https://github.com/apache/spark/blob/master/core/src/main/java/org/apache/spark/util/collection/TimSort.java#L18)，就是基于`Android Open Source Project`的`TimSort.java`改造的。这种情况[Spark](https://github.com/apache/spark)会在[TimSort.java](https://github.com/apache/spark/blob/master/core/src/main/java/org/apache/spark/util/collection/TimSort.java#L18)中声明对`Android Open Source Project`的`TimSort.java`的引用，并保留原作者的Copyright，同时在[LICENSE](https://github.com/apache/spark/blob/master/LICENSE#L214)文件中声明后者相关的`LICENSE`。如果第三方依赖的`LICENSE`与项目的`LICENSE`不同，或者不适合在代码中体现时，[Spark](https://github.com/apache/spark)则会为他们在[licenses](https://github.com/apache/spark/tree/master/licenses)目录添加一份`LICENSE`副本。我想说的是，我们在使用或修改第三方源码的时候，能否学习[Spark](https://github.com/apache/spark)的做法。

另外，发布`RELEASE`包的时候，如果需要带上使用或修改了第三方依赖源码的类时，应当把带有相关声明的`LICENSE`文件和`licenses`目录打入`RELEASE`包中。至于使用`maven-shade-plugin`、`maven-assembly-plugin`、`spring-boot-maven-plugin`等打包插件将第三方依赖的二进制文件打入`RELEASE`包的场景，[Spark](https://github.com/apache/spark)的做法则是专门为二进制包创建[LICENSE-binary](https://github.com/apache/spark/blob/master/LICENSE-binary#L408)文件和[licenses-binary](https://github.com/apache/spark/tree/master/licenses-binary)文件夹，在使用[make-distribution.sh](https://github.com/apache/spark/blob/master/dev/make-distribution.sh#L216)发布产品的时候，将他们重命名为`LICENSE`文件和`licenses`文件夹带上。我想，这种做法我们是否可以借鉴一下，这可能对以后我们发布`RELEASE`包的时候会有很大帮助。

最后，我们可能还需要补充`Description`项目描述、`Code of conduct`行为准则和`Contributing`文件。

**Comment by WillemJiang** [comment]
的确，如果第三方代码的源文件是需要保留之前的License声明的。 详细操作指导可以参考 [这里](https://www.apache.org/legal/src-headers.html#3party)，基本上Spark的例子差不多。 至于更新LICENSE说明是因为源代码包打包的时候包含了这部分第三方的工作，我们需要在[LICENSE中进行说明](https://github.com/huaweicloud/java-mesh/issues/164#issuecomment-985145165)。 

二进制release发布的，只要是我们把第三方的依赖包打进去了，就是需要在LICENSE文件中加以说明， [在这个issue回复](https://github.com/huaweicloud/java-mesh/issues/164#issuecomment-985145165)中我已经说明了，你可以参考Spark的做法，或者[servicecomb-pack的做法](https://github.com/apache/servicecomb-pack/tree/master/distribution)。

**Comment by WillemJiang** [comment]
其他的描述文件也可以参考比较流行的项目一并加上，方便用户参与贡献。
