### ISSUE TITLE
how to add a annotation to a method sermant ?

### ISSUE THREAD

**Issue by whispin** [huaweicloud/Sermant#379]
question description：
Hi,
I want to add an annotation to a method and not to change the original method body.

example:

origin

`public class Bar {
  public  String m(){
   return "bar" ;
  }
} `

redefined

`public class Bar  {
@MyAnnotation
  public  String m(){
   return "bar" ;
  }`

I don't know how to write the intercepter that don't change the method body just add an Annotation  with `com.huawei.sermant.core.plugin.agent.interceptor.Interceptor`

THX!

**Comment by HapThorin** [comment]
For sermant, it's not supported to add annotations by bytecode enhancing. Typically, annotations in runtime scope are used for defining special invoke strategy, which absolutely can be defined in `Interceptor` instead.
