### ISSUE TITLE
实现了PluginDeclarer，但是启动agent时未加载实现类

### ISSUE THREAD

**Issue by SamuelChan1433** [huaweicloud/Sermant#534]
question description：
public abstract class AbstractPluginDeclarer implements PluginDeclarer{}

public class RedissonClusterDeclarer extends AbstractPluginDeclarer {}

实际执行工程时，RedissonClusterDeclarer未被加载进来。
sermant版本release 0.2.0

**Comment by luanwenfei-venus** [comment]
是否定义了spi文件（META-INF/services/com.huawei.sermant.core.plugin.agent.declarer.PluginDeclarer）？
