### ISSUE TITLE
How Sermant  resolve rocketmq,mysql or other middleware stream control?  

### ISSUE THREAD

**Issue by gy09535** [huaweicloud/Sermant#568]

**Comment by luanwenfei-venus** [comment]
You can speak Chinese.What does “stream control” mean."How to control stream" or "How to operation stream(like io stream)".

**Comment by gy09535** [comment]
> You can speak Chinese.What does “stream control” mean."How to control stream" or "How to operation stream(like io stream)".
好的，感谢回复。这里的流量控制主要指的是网络流量控制，比如：http 请求信息，需求根据一些特定请求头来做特定的转发逻辑。比如：应用程序（JAVA 应用）在访问消息队列时，根据当前线程的上下文信息或者特定协议的附加信息（JMS message 的消息头部信息）来决定将消息投递给相应的的主题（队列）等。

**Comment by luanwenfei-venus** [comment]
> > You can speak Chinese.What does “stream control” mean."How to control stream" or "How to operation stream(like io stream)".
> 
> 好的，感谢回复。这里的流量控制主要指的是网络流量控制，比如：http 请求信息，需求根据一些特定请求头来做特定的转发逻辑。比如：应用程序（JAVA 应用）在访问消息队列时，根据当前线程的上下文信息或者特定协议的附加信息（JMS message 的消息头部信息）来决定将消息投递给相应的的主题（队列）等。

明白的，目前我们并没有做对类似mysql等中间件的流量控制，但是可以在此框架基础上开发此类功能，期待您的贡献
